# Tutorial
The tutorial is based on the Software Carpentry intro to Python:
- https://github.com/swcarpentry/python-novice-inflammation
- https://swcarpentry.github.io/python-novice-inflammation/01-numpy

# Setup
- https://swcarpentry.github.io/python-novice-inflammation/setup

In [ ]:
mkdir swc-python

In [ ]:
cd swc-python

In [ ]:
!wget https://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip
!wget https://swcarpentry.github.io/python-novice-inflammation/code/python-novice-inflammation-code.zip

In [ ]:
!unzip python-novice-inflammation-data.zip
!unzip python-novice-inflammation-code.zip

In [ ]:
cd data

In [ ]:
!ls -al

## Variables

Any Python interpreter can be used as a calculator:

In [ ]:
3 + 5 * 4

This is great but not very interesting.
To do anything useful with data, we need to assign its value to a _variable_.
In Python, we can assign a value to a variable, using the equals sign `=`.
For example, to assign value `60` to a variable `weight_kg`, we would execute:

In [ ]:
weight_kg = 60

From now on, whenever we use `weight_kg`, Python will substitute the value we assigned to
it. In essence, **a variable is just a name for a value**.

In Python, variable names:

 - can include letters, digits, and underscores
 - cannot start with a digit
 - are case sensitive.

This means that, for example:
 - `weight0` is a valid variable name, whereas `0weight` is not
 - `weight` and `Weight` are different variables


## Types of data
Python knows various types of data. Three common ones are:

* integer numbers
* floating point numbers, and
* strings.

In the example above, variable `weight_kg` has an integer value of `60`.
To create a variable with a floating point value, we can execute:

In [ ]:
weight_kg = 60.0

And to create a string we simply have to add single or double quotes around some text, for example:

In [ ]:
weight_kg_text = 'weight in kilograms:'

## Using Variables in Python
To display the value of a variable to the screen in Python, we can use the `print` function:

In [ ]:
print(weight_kg)

We can display multiple things at once using only one `print` command:

In [ ]:
print(weight_kg_text, weight_kg)

Moreover, we can do arithmetic with variables right inside the `print` function:

In [ ]:
print('weight in pounds:', 2.2 * weight_kg)

The above command, however, did not change the value of `weight_kg`:

In [ ]:
print(weight_kg)

To change the value of the `weight_kg` variable, we have to
**assign** `weight_kg` a new value using the equals `=` sign:

In [ ]:
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)

While a lot of powerful, general tools are built into Python, specialized tools built up from these basic units live in _libraries_ that can be called upon when needed.

## Loading data into Python
In order to load our inflammation data, we need to access
("import" in Python terminology) a library called
[NumPy](http://docs.scipy.org/doc/numpy/ "NumPy Documentation").  In general you should use this
library if you want to do fancy things with numbers, especially if you have matrices or arrays.  We
can import NumPy using:

In [ ]:
import numpy

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it
up on the bench. Libraries provide additional functionality to the basic Python package, much like
a new piece of equipment adds functionality to a lab space. Just like in the lab, importing too
many libraries can sometimes complicate and slow down your programs - so we only import what we
need for each program. Once we've imported the library, we can ask the library to read our data
file for us:


In [ ]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

The expression `numpy.loadtxt(...)` is a _function call_ that asks Python to run the _function_ `loadtxt` which belongs to the `numpy` library. This _dotted notation_ is used everywhere in Python: the thing that appears before the dot contains the thing that appears after.

As an example, John Smith is the John that belongs to the Smith family.
We could use the dot notation to write his name `smith.john`,
just as `loadtxt` is a function that belongs to the `numpy` library.

`numpy.loadtxt` has two _parameters_: the name of the file we want to read and the delimiter that separates values on
a line. These both need to be character strings (or strings for short), so we put them in quotes.

Since we haven't told it to do anything else with the function's output, the notebook displays it.
In this case, that output is the data we just loaded.
By default, only a few rows and columns are shown
(with `...` to omit elements when displaying big arrays). To save space, Python displays numbers as `1.` instead of `1.0` when there's nothing interesting after the decimal point.

Our call to `numpy.loadtxt` read our file
but didn't save the data in memory.
To do that, we need to assign the array to a variable. Just as we can assign a single value to a variable, we
can also assign an array of values to a variable using the same syntax.  Let's re-run
`numpy.loadtxt` and save the returned data:

In [ ]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

This statement doesn't produce any output because we've assigned the output to the variable `data`.
If we want to check that the data have been loaded,
we can print the variable's value:

In [ ]:
print(data)

Now that the data are in memory,
we can manipulate them.
First, let's ask what _type_ of thing `data` refers to:

In [ ]:
print(type(data))

The output tells us that `data` currently refers to
an N-dimensional array, the functionality for which is provided by the NumPy library.
These data correspond to arthritis patients' inflammation.
The rows are the individual patients, and the columns
are their daily inflammation measurements.


## Data Type

A Numpy array contains one or more elements
of the same type. The `type` function will only tell you that a variable is a NumPy array but won't tell you the type of thing inside the array.
We can find out the type of the data contained in the NumPy array.


In [ ]:
print(data.dtype)

This tells us that the NumPy array's elements are
_floating-point numbers_.

With the following command, we can see the array's _shape_:

In [ ]:
print(data.shape)

The output tells us that the `data` array variable contains 60 rows and 40 columns. When we
created the variable `data` to store our arthritis data, we didn't just create the array; we also
created information about the array, called attributes. `data.shape` is an attribute of `data` which describes the dimensions of `data`. We use the same dotted notation for the attributes of variables that we use for the functions in libraries because
they have the same part-and-whole relationship.


If we want to get a single number from the array, we must provide an _index_ in square brackets after the variable name, just as we do in math when referring to an element of a matrix.  Our inflammation data has two dimensions, so we will need to use two indices to refer to one specific value:

In [ ]:
print('first value in data:', data[0, 0])

In [ ]:
print('middle value in data:', data[30, 20])

The expression `data[30, 20]` accesses the element at row 30, column 20. While this expression may
not surprise you,
 `data[0, 0]` might.

Programming languages like Fortran, MATLAB and R start counting at 1
because that's what human beings have done for thousands of years.

Languages in the C family (including C++, Java, Perl, and Python) count from 0
because it represents an offset from the first value in the array (the second
value is offset by one index from the first value). This is closer to the way
that computers represent arrays (if you are interested in the historical
reasons behind counting indices from zero, you can read
[Mike Hoye's blog post](http://exple.tive.org/blarg/2013/10/22/citation-needed/)).

As a result,
if we have an M×N array in Python,
its indices go from 0 to M-1 on the first axis
and 0 to N-1 on the second.
It takes a bit of getting used to,
but one way to remember the rule is that
the index is how many steps we have to take from the start to get the item we want.


> ## In the Corner
>
> What may also surprise you is that when Python displays an array,
> it shows the element with index `[0, 0]` in the upper left corner
> rather than the lower left.
> This is consistent with the way mathematicians draw matrices
> but different from the Cartesian coordinates.
> The indices are (row, column) instead of (column, row) for the same reason,
> which can be confusing when plotting data.


## Slicing data
An index like `[30, 20]` selects a single element of an array,
but we can select whole sections as well.
For example,
we can select the first ten days (columns) of values
for the first four patients (rows) like this:


In [ ]:
print(data[0:4, 0:10])

The _slice_ `0:4` means, "Start at index 0 and go up to, but not including, index 4."

Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

We don't have to start slices at 0:


In [ ]:
print(data[5:10, 0:10])

We also don't have to include the upper and lower bound on the slice.  If we don't include the lower
bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the
axis, and if we don't include either (i.e., if we just use ':' on its own), the slice includes
everything:


In [ ]:
small = data[:3, 36:]
print('small is:')
print(small)

The above example selects rows 0 through 2 and columns 36 through to the end of the array.


Arrays also know how to perform common mathematical operations on their values.  The simplest
operations with data are arithmetic: addition, subtraction, multiplication, and division.  When you
do such operations on arrays, the operation is done element-by-element.  Thus:

In [ ]:
doubledata = data * 2.0

will create a new array `doubledata`
each element of which is twice the value of the corresponding element in `data`:

In [ ]:
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])

If, instead of taking an array and doing arithmetic with a single value (as above), you did the
arithmetic operation with another array of the same shape, the operation will be done on
corresponding elements of the two arrays.  Thus:

In [ ]:
tripledata = doubledata + data

will give you an array where `tripledata[0,0]` will equal `doubledata[0,0]` plus `data[0,0]`,
and so on for all other elements of the arrays.

In [ ]:
print('tripledata:')
print(tripledata[:3, 36:])

Often, we want to do more than add, subtract, multiply, and divide array elements.  NumPy knows how
to do more complex operations, too.  If we want to find the average inflammation for all patients on
all days, for example, we can ask NumPy to compute `data`'s mean value:


In [ ]:
print(numpy.mean(data))

`mean` is a _function_ that takes
an array as an _argument_.

> ## **Note**: Not All Functions Have Input
> 
> Generally, a function uses inputs to produce outputs.
> However, some functions produce outputs without
> needing any input. For example, checking the current time doesn't require any input.

In [ ]:
import time
print(time.ctime())

> For functions that don't take in any arguments,
> we still need parentheses (`()`)
> to tell Python to go and do something for us.

NumPy has lots of useful functions that take an array as input.
Let's use three of those functions to get some descriptive values about the dataset.
We'll also use multiple assignment,
a convenient Python feature that will enable us to do this all in one line.

In [ ]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

Here we've assigned the return value from `numpy.max(data)` to the variable `maxval`, the value
from `numpy.min(data)` to `minval`, and so on.

> ## Mystery Functions in IPython
>
> How did we know what functions NumPy has and how to use them?
> If you are working in IPython or in a Jupyter Notebook, there is an easy way to find out.
> If you type the name of something followed by a dot, then you can use tab completion
> (e.g. type `numpy.` and then press tab)
> to see a list of all functions and attributes that you can use. After selecting one, you
> can also add a question mark (e.g. `numpy.cumprod?`), and IPython will return an
> explanation of the method! This is the same as doing `help(numpy.cumprod)`.


When analyzing data, though,
we often want to look at variations in statistical values,
such as the maximum inflammation per patient
or the average inflammation per day.
One way to do this is to create a new temporary array of the data we want,
then ask it to do the calculation:


In [ ]:
patient_0 = data[0, :] # 0 on the first axis (rows), everything on the second (columns)
print('maximum inflammation for patient 0:', numpy.max(patient_0))


Everything in a line of code following the '#' symbol is a
_comment_ that is ignored by Python.
Comments allow programmers to leave explanatory notes for other
programmers or their future selves.

We don't actually need to store the row in a variable of its own.
Instead, we can combine the selection and the function call:

In [ ]:
print('maximum inflammation for patient 2:', numpy.max(data[2, :]))

What if we need the maximum inflammation for each patient over all days or the average for each day? As the diagram at https://swcarpentry.github.io/python-novice-inflammation/01-numpy/index.html shows, we want to perform the operation across an axis.

To support this functionality,
most array functions allow us to specify the axis we want to work on.
If we ask for the average across axis 0 (rows in our 2D example),
we get:

In [ ]:
print(numpy.mean(data, axis=0))

As a quick check,
we can ask this array what its shape is:

In [ ]:
print(numpy.mean(data, axis=0).shape)

The expression `(40,)` tells us we have an N×1 vector,
so this is the average inflammation per day for all patients.
If we average across axis 1 (columns in our 2D example), we get:

In [ ]:
print(numpy.mean(data, axis=1))

which is the average inflammation per patient across all days.

## Visualizing data
The mathematician Richard Hamming once said, "The purpose of computing is insight, not numbers," and
the best way to develop insight is often to visualize data.  Visualization deserves an entire
lecture of its own, but we can explore a few features of Python's `matplotlib` library here.  While
there is no official plotting library, `matplotlib` is the _de facto_ standard.  First, we will
import the `pyplot` module from `matplotlib` and use two of its functions to create and display a
heat map of our data:

In [ ]:
%matplotlib widget
import matplotlib.pyplot
image = matplotlib.pyplot.imshow(data)
# matplotlib.pyplot.show()

Blue pixels in this heat map represent low values, while yellow pixels represent high values.  As we
can see, inflammation rises and falls over a 40-day period.

Let's take a look at the average inflammation over time:

In [ ]:
matplotlib.pyplot.figure()
ave_inflammation = numpy.mean(data, axis=0)
ave_plot = matplotlib.pyplot.plot(ave_inflammation)

Here, we have put the average per day across all patients in the variable `ave_inflammation`, then
asked `matplotlib.pyplot` to create and display a line graph of those values.  The result is a
roughly linear rise and fall, which is suspicious: we might instead expect a sharper rise and slower
fall.  Let's have a look at two other statistics:

In [ ]:
matplotlib.pyplot.figure()
max_plot = matplotlib.pyplot.plot(numpy.max(data, axis=0))

In [ ]:
matplotlib.pyplot.figure()
min_plot = matplotlib.pyplot.plot(numpy.min(data, axis=0))

The maximum value rises and falls smoothly, while the minimum seems to be a step function.  Neither
trend seems particularly likely, so either there's a mistake in our calculations or something is
wrong with our data.  This insight would have been difficult to reach by examining the numbers
themselves without visualization tools.

### Grouping plots
You can group similar plots in a single figure using subplots.
This script below uses a number of new commands. The function `matplotlib.pyplot.figure()`
creates a space into which we will place all of our plots. The parameter `figsize`
tells Python how big to make this space. Each subplot is placed into the figure using
its `add_subplot` [method]({{ page.root }}/reference/#method). The `add_subplot` method takes 3
parameters. The first denotes how many total rows of subplots there are, the second parameter
refers to the total number of subplot columns, and the final parameter denotes which subplot
your variable is referencing (left-to-right, top-to-bottom). Each subplot is stored in a
different variable (`axes1`, `axes2`, `axes3`). Once a subplot is created, the axes can
be titled using the `set_xlabel()` command (or `set_ylabel()`).
Here are our three plots side by side:


In [ ]:
import numpy
import matplotlib.pyplot

data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

axes1 = fig.add_subplot(1, 3, 1)
axes2 = fig.add_subplot(1, 3, 2)
axes3 = fig.add_subplot(1, 3, 3)

axes1.set_ylabel('average')
axes1.plot(numpy.mean(data, axis=0))

axes2.set_ylabel('max')
axes2.plot(numpy.max(data, axis=0))

axes3.set_ylabel('min')
axes3.plot(numpy.min(data, axis=0))

fig.tight_layout()

The call to `loadtxt` reads our data,
and the rest of the program tells the plotting library
how large we want the figure to be,
that we're creating three subplots,
what to draw for each one,
and that we want a tight layout.
(If we leave out that call to `fig.tight_layout()`,
the graphs will actually be squeezed together more closely.)


> ## Scientists Dislike Typing
>
> We will always use the syntax `import numpy` to import NumPy.
> However, in order to save typing, it is
> [often suggested](http://www.scipy.org/getting-started.html#an-example-script)
> to make a shortcut like so: `import numpy as np`.
> If you ever see Python code online using a NumPy function with `np`
> (for example, `np.loadtxt(...)`), it's because they've used this shortcut.
> When working with other people, it is important to agree on a convention of how common libraries
> are imported.


## Check Your Understanding

What values do the variables `mass` and `age` have after each statement in the following program?
Test your answers by executing the commands.
```python
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass, age)
```

In [ ]:
# Your code goes here:


## Sorting Out References

What does the following program print out?

```python
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)
```

In [ ]:
# Your code goes here:


## Slicing Strings

A section of an array is called a [slice]({{ page.root }}/reference/#slice).
We can take slices of character strings as well:

```python
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
```

```
first three characters: oxy
last three characters: gen
```

What is the value of `element[:4]`?
What about `element[4:]`?
Or `element[:]`?

In [ ]:
# Your code goes here:


What is `element[-1]`?
What is `element[-2]`?

In [ ]:
# Your code goes here:


Given those answers,
explain what `element[1:-1]` does.

In [ ]:
# Your code goes here:


## Thin Slices

The expression `element[3:3]` produces an empty string,
i.e., a string that contains no characters.
If `data` holds our array of patient data,
what does `data[3:3, 4:4]` produce?
What about `data[3:3, :]`?


In [ ]:
# Your code goes here:



## Plot Scaling

Why do all of our plots stop just short of the upper end of our graph?

If we want to change this, we can use the `set_ylim(min, max)` method of each 'axes',
for example:
```python
axes3.set_ylim(0,6)
```

Update your plotting code to automatically set a more appropriate scale.
(Hint: you can make use of the `max` and `min` methods to help.)

In [ ]:
# Your code goes here:


## Make Your Own Plot

Create a plot showing the standard deviation (`numpy.std`)
of the inflammation data for each day across all patients.

In [ ]:
# Your code goes here:


## Moving Plots Around

Modify the program to display the three plots on top of one another
instead of side by side.

In [ ]:
# Your code goes here:



## Stacking Arrays

Arrays can be concatenated and stacked on top of one another,
using NumPy's `vstack` and `hstack` functions for vertical and horizontal stacking, respectively.

```python
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)
```

```
A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C =
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
```

Write some additional code that slices the first and last columns of `A`,
and stacks them into a 3x2 array.
Make sure to `print` the results to verify your solution.

In [ ]:
# Your code goes here:


## Change In Inflammation

This patient data is _longitudinal_ in the sense that each row represents a
series of observations relating to one individual.  This means that
the change in inflammation over time is a meaningful concept.

The `numpy.diff()` function takes a NumPy array and returns the
differences between two successive values along a specified axis.  For
example, a NumPy array that looks like this:

```python
npdiff = numpy.array([ 0,  2,  5,  9, 14])
```

Calling `numpy.diff(npdiff)` would do the following calculations and
put the answers in another array.

```python
[ 2 - 0, 5 - 2, 9 - 5, 14 - 9 ]
```

```python
numpy.diff(npdiff)
```

```python
array([2, 3, 4, 5])
```

Which axis would it make sense to use this function along?